language: python

python:
  - "3.4"
  - "3.5"

sudo: required

before_install:
  - git submodule update --init --recursive

install:
  - pip3 install coveralls

script:
  - git clone https://github.com/PedalPi/PedalPi-Raspberry.git PedalPi
  - git checkout baaff54
  - cd PedalPi
  - pip3 install -r requirements.txt
  - cd ..
  - python3 PedalPi/start.py &
  - sleep 10
  - coverage3 run --source=handler setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
