language: python

python:
  - "3.4"

sudo: required

before_install:
  - git submodule update --init --recursive

install:
  - pip3 install coveralls

script:
  - python3 start.py &
  - coverage3 run --source=handler setup.py test
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
