language: python
python:
  - '3.4'
  - '3.5'
  - 3.6-dev
  - nightly
sudo: required
before_install:
  - npm install -g dredd@3.4.1
before_script:
  - dredd
install:
  - sudo apt-get install libavahi-compat-libdnssd1
  - python setup.py install
script:
  - cd test/
  - python config.py &
  - sleep 5
  - cd ..
  - coverage3 run --source=handler setup.py test
after_success:
  - coveralls
  - 'bash <(curl -s https://codecov.io/bash)'
