language: python

python:
  - "3.4"
  - "3.5"
  - "nightly"

sudo: required

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get install libavahi-compat-libdnssd1
  - pip3 install -r requirements.txt

script:
  - cd ..
  - mv WebService webservice
  - mv webservice/test/config.py config.py
  - git clone --recursive https://github.com/PedalPi/Application.git Application --depth=1
  - cd Application
  - python setup.py develop
  - cd ..
  - python3 config.py &
  - sleep 5
  - cd webservice
  - coverage3 run --source=handler setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
