language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

jobs:
  include:
    - stage: unit-test
      script: make test
    - stage: doc
      script:
        - make install-docs-requirements
        - make test

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
