language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends
  - sudo apt-get install -y libavahi-compat-libdnssd1 --no-install-recommends
  - pip3 install coveralls
  - pip3 install git+https://github.com/depl0y/pybonjour-python3
  - pip3 install zeroconf
  - python3 setup.py develop

script:
  - lv2ls
  - coverage3 run --source=webservice wstest/config.py test

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
