language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

sudo: required

install:
  - sudo apt-get install libavahi-compat-libdnssd1
  - pip setup.py install

script:
  - cd test/
  - python config.py &
  - sleep 5
  - cd ..
  - coverage3 run --source=handler setup.py test

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
