#%RAML 1.0
title: Pedal PI - Web Service
version: v0.0.1
baseUri: /
mediaType:  application/json
description:
  Manage the Pedal Pi by REST API

/effects:
  description: Obtains all plugins effects installed data
  get:
    description: Get all plugins effects installed

/banks:
  description: Obtains all banks data persisted in Pedal Pi
  get:
    description: Get all banks

/bank:
  post:
    description:
      Post a new bank. A new bank index is returned

  /{bankIndex}:
    uriParameters:
      bankIndex:
        description: Bank index
        type: integer
    get:
      description: Get a bank
    put:
      description: Update a bank
    delete:
      description: Delete a bank

    /patch:
      post:
        description: Post a new patch
      /{patchIndex}:
        uriParameters:
          patchIndex:
            description: Patch index
            type: integer
        get:
          description: Get a patch
        put:
          description: Update a patch
        delete:
          description: Remove a effect

        /effect:
          post:
            description: Post a new effect
          /{effectIndex}:
            uriParameters:
              effectIndex:
                description: Effect index
                type: integer

            get:
              description: Get an effect
            delete:
              description: Remove an effect

            /param/{paramIndex}:
              uriParameters:
                paramIndex:
                  description: Param index
                  type: integer
              get:
                description: Get a param
              put:
                description: Update the param value

/data/{key}:
  description: |
    Not implemented yet.
    Save consumer and manage data in valid json-format.
  uriParameters:
    key:
      description: Key idenfier. Util then more one application saves data in patch
  get:
    description:
      Get the patch data based in key sended
    responses:
      200:
        body:
          application/json:
            examples:
              Empty: {}
              Any content: {any-key: any-data}

  post:
    description:
      Saves the patch data. If exists a data in key defined, will be overrided
    body:
      application/json:
        example: {any-key: any-data}

  delete:
    description:
      Removes the patch data for the key defined

/current:
  description: Manage the current patch
  get:
    description: Get the current bank index and the current patch index
  /data:
    get:
      description: Get the current bank data and the current patch index

  /bank/{bankIndex}/patch/{patchIndex}:
    uriParameters:
      bankIndex:
        type: integer
      patchIndex:
        type: integer
    put:
      description: Put the current bankIndex and the current patchIndex

  /effect/{effectIndex}:
    uriParameters:
      effectIndex:
        type: integer
    put:
      description: Put for toggle effect status (active for bypassed or bypassed for active) of the current patch

    /param/{paramIndex}:
      uriParameters:
        paramIndex:
          type: integer
      put:
        description: Put for set a parameter value for a effect of the current patch

/swap:
  description: Deprecated

/connections:
  description: Not implemented yet

/peripheral:
  description: Not implemented yet
