FORMAT: 1A
HOST: http://pedalpi.local:3000/v1

# Pedal PI - WebService - API documentation

**Pedal Pi - WebService** is a [Pedal Pi component](https://github.com/PedalPi/Components#components) that offers a Pedal Pi management over REST + WebSocket. This documentation describes the REST API.

# Group Authentication

<!-- include(section/authentication.apib) -->

# Group Plugins management

<!-- include(section/plugins.apib) -->

# Group Banks management

<!-- include(section/banks.apib) -->

# Group Bank management

<!-- include(section/bank.apib) -->

# Group Pedalboard management

<!-- include(section/pedalboard.apib) -->

# Group Pedalboard Data management

<!-- include(section/pedalboard_data.apib) -->

# Group Effect management

<!-- include(section/effect.apib) -->

# Group Param management

<!-- include(section/param.apib) -->

# Group Effect connections management

<!-- include(section/connection.apib) -->

# Group Current management

<!-- include(section/current.apib) -->

# Group Swap management

Not implemented yet

# Group ComponentDataHandler

Has been implemented?

# Group WebSocket

It's necessaty specify the updates notification types
