# Group data

## Data By Key [/data/{key}]

+ Parameters
    + key (string, required)

        Key idenfier. Util then more one application saves data in pedalboard


### DataByKey [GET]
Get the pedalboard data based in key sended

+ Response 200
    + Attributes (string)


### DataByKey [POST]
Saves the pedalboard data. If exists a data in key defined, will be overrided

+ Request
    + Attributes (string)
+ Response 200

### DataByKey [DELETE]
Removes the pedalboard data for the key defined

+ Response 200

# Group current
