Manages the banks data.

## Banks [/banks]

### List banks [GET]
Get all banks

+ Request  (application/json; charset=UTF-8)

    + Headers

            Authorization: bearer <auth token>

+ Response 200 (application/json; charset=UTF-8)

   + Body

            {
              "banks": {
                "0": {"index": 0, ...},
                "1": {"index": 0, ...}
              }
            }
