Manages the banks data.

## Banks [/banks]

### Banks [GET]
Get all banks

+ Response 200 (application/json; charset=UTF-8)
   + Body

            {
              "banks": {
                "0": {"index": 0, ...},
                "1": {"index": 0, ...}
              }
            }
