It's possible obtains the Lv2Plugins data in a json format. Pedal Pi uses [lilvlib](https://github.com/moddevices/lilvlib) for parse to json.

## Plugins [/plugins]

### Plugins list [GET]

Get all audio plugins installed

+ Request  (application/json; charset=UTF-8)

    + Headers

            Authorization: bearer <auth token>

+ Response 200 (application/json; charset=UTF-8)
   + Body

            {
                "plugins": [
                    /* Plugins list */
                    {"presets": [], ...},
                ]
            }

## Reload plugins [/plugins/reload]

### Reload plugins [PUT]

Reloads the lv2 plugins data.

To get the audio plugin metadata, you need to install lilv. Check the [`Lv2EffectBuilder.lv2_plugins_data()` method documentation](http://pedalpi-pluginsmanager.readthedocs.io/model_lv2.html#pluginsmanager.model.lv2.lv2_effect_builder.Lv2EffectBuilder.lv2_plugins_data) for more details on how to install.

If `lilv` is not installed, an error (400) is returned.

+ Request  (application/json; charset=UTF-8)

    + Headers

            Authorization: bearer <auth token>

+ Response 200 (application/json; charset=UTF-8)
   + Body

            {
              "status": "ok"
            }
+ Response 400 (application/json; charset=UTF-8)
   + Body

            {
              "error": "lilv not configured"
            }

## Plugin [/plugin/{uri}]

### Plugin data [GET]

Get a specific audio plugin json by `uri` identifier.

::: note
Some audio plugins have their uri containing **`#`**. To get the plugin data,
you need to replace **`#`** with **`%23`**.

Example:

* Replace
```
plugin/http://guitarix.sourceforge.net/plugins/gx_redeye#chump
```
* with
```
plugin/http://guitarix.sourceforge.net/plugins/gx_redeye%23chump
```
:::

+ Parameters
    + uri: `http://calf.sourceforge.net/plugins/MonoInput` (required, string) - The plugin URI

+ Request  (application/json; charset=UTF-8)

    + Headers

            Authorization: bearer <auth token>
+ Response 200 (application/json; charset=UTF-8)
    + Body

            <!-- include(plugin.json) -->

    + Schema

            Not defined
+ Response 400 (application/json; charset=UTF-8)

    + Body

            {"error": "Plugin \"https://github.com/ninodewit/SHIRO-Plugins/plugins/larynx\" not installed"}
